### ISSUE TITLE
Formating issue in unicode character folding chapter

### ISSUE THREAD

**Issue by robertlyson** [elasticsearch/elasticsearch-definitive-guide#292]
Hello,

Looks like part of second paragraph in [unicode character folding](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/character-folding.html) chapter is highlighted incorrectly. 

![image](https://cloud.githubusercontent.com/assets/2392583/5605256/bfc94bce-93f1-11e4-971e-98305243eb60.png)

**Comment by clintongormley** [comment]
thanks for reporting @robertlyson - fixed
