### ISSUE TITLE
pleeas., help me...

### ISSUE THREAD

**Issue by drscg** [elasticsearch/elasticsearch-definitive-guide#293]
I'm a C and Java developer who works in Korea.
I've seen the Elasticsearch by chance and read the manual for development.
and i was greedy, so began the translating(in korean) of the book (Elasticsearch: the definitive guide).
those translating, searching and elasticsearch were all first time to me.

I've done the translating around in 3 months and i hoped for publishing it in Korea.
But it was canceled because of a conflict of opinion between publisher and writer.
The writer's opinion what i've heard from publisher was that he has required for copyright and posting that translated one online.
Korea is not a country which books are sold a lot, therefore his requirements might not be acceptable in publisher's side.
It seems why the publisher canceled for the translation copy was because of that.
However, I want to publish this in any case.
and also, I'm willing to post this online, but i wish to have some payment.

please tell me if there's any solution of this situation.
thank you...

**Comment by clintongormley** [comment]
Hi @drscg 

Please contact me at clinton dot gormley at elasticsearch dot com.

thanks
